grzi/scion

examples/taquin/main.rs, examples/tetris/main.rs, src/rendering/bidimensional/components/mod.rs, src/rendering/bidimensional/components/triangle.rs, src/rendering/bidimensional/components/ui/mod.rs, src/rendering/bidimensional/components/ui/ui_image.rs, src/rendering/bidimensional/gl_representations.rs, src/rendering/bidimensional/mod.rs, src/rendering/bidimensional/scion2d.rs, src/rendering/bidimensional/transform.rs
=> feat: UiImage and layer rendering

examples/taquin/main.rs, examples/tetris/layer.rs, examples/tetris/systems/move_system.rs, examples/tetris/systems/piece_system.rs, examples/tetris/systems/rotation_system.rs, examples/tetris/systems/score_system.rs, src/core/components/maths/transform.rs, src/core/systems/ui_text_system.rs, src/rendering/bidimensional/gl_representations.rs, src/rendering/bidimensional/scion2d.rs, src/rendering/shaders/shader.frag, src/rendering/shaders/shader.vert
examples/tetris/layer.rs
examples/tetris/system/piece_system.rs
examples/tetris/system/score_system.rs
examples/tetris/system/move_system.rs
examples/tetris/system/rotate_system.rs
examples/taquin/main.rs
src/core/systems/ui_text_system.rs
src/core/components/maths/transform.rs
src/rendering/bidimensional/gl_representations.rs
src/rendering/bidimensional/scion2d.rs
=> changed Transform2D to Transform in 10 files

examples/mario/main.rs, examples/tetris/systems/move_system.rs, examples/tetris/systems/piece_system.rs, src/application.rs, src/core/components/maths/camera.rs, src/core/components/ui/mod.rs, src/core/systems/missing_ui_component_system.rs, src/core/systems/mod.rs, src/core/systems/ui_text_system.rs, src/rendering/bidimensional/gl_representations.rs, src/rendering/bidimensional/scion2d.rs
FIXES #73 
This also lock the ui components. Meaning that the camera position has no impact on the ui components
=> feat: camera position in 2D world

examples/mario/main.rs, src/core/components/mod.rs, src/core/components/shapes/square.rs, src/core/components/shapes/triangle.rs, src/core/components/sprite.rs, src/core/components/ui/ui_image.rs, src/core/components/ui/ui_text.rs, src/rendering/bidimensional/scion2d.rs
=> feat: add Sprite component

examples/mario/main.rs, examples/taquin/main.rs, examples/tetris/main.rs, src/core/game_layer.rs
=> feat: layer replacement

src/application.rs, src/core/components/maths/collider.rs, src/core/components/maths/mod.rs, src/core/systems/collider_systems.rs, src/core/systems/mod.rs
=> feat: add simple square colliders

Cargo.toml, src/config/window_config.rs, src/rendering/bidimensional/gl_representations.rs, src/rendering/bidimensional/scion2d.rs, src/rendering/renderer_state.rs, src/rendering/shaders/pipeline.rs
=> tech: Upgrade winit, wgpu, bytemuck and serde

examples/mario/main.rs, examples/taquin/main.rs, examples/tetris/layer.rs, src/core/components/maths/camera.rs, src/core/components/maths/transform.rs, src/core/event_handler.rs, src/core/systems/hierarchy_system.rs, src/core/systems/ui_text_system.rs, src/rendering/bidimensional/gl_representations.rs, src/rendering/bidimensional/scion2d.rs, src/rendering/mod.rs, src/rendering/renderer_state.rs
=> feat: Move Camera to world and add bounds to Transform

examples/mario/main.rs, examples/taquin/main.rs, examples/tetris/layer.rs, examples/tetris/systems/piece_system.rs, src/core/components/material.rs, src/core/components/maths/camera.rs, src/core/components/maths/transform.rs, src/core/components/mod.rs, src/core/components/shapes/rectangle.rs, src/core/components/shapes/square.rs, src/core/components/shapes/triangle.rs, src/core/components/tiles/mod.rs, src/core/components/tiles/sprite.rs, src/core/components/tiles/tileset.rs, src/core/components/ui/ui_image.rs, src/core/components/ui/ui_text.rs, src/core/event_handler.rs, src/core/resources/asset_manager.rs, src/core/systems/hierarchy_system.rs, src/core/systems/ui_text_system.rs, src/rendering/bidimensional/scion2d.rs, src/rendering/mod.rs, src/rendering/renderer_state.rs
=> feat: tileset material loadable in asset manager

examples/bomberman/main.rs, examples/tetris/layer.rs, examples/tetris/systems/piece_system.rs, src/application.rs, src/config/window_config.rs, src/core/components/animations.rs, src/core/components/color.rs, src/core/components/mod.rs, src/core/event_handler.rs, src/core/resources/time.rs, src/core/systems/animations_system.rs, src/core/systems/mod.rs, src/rendering/bidimensional/scion2d.rs, src/rendering/mod.rs, src/rendering/renderer_state.rs
FIXES #122
FIXES #104
FIXES #129
=> feat: Global animations component and Transform animation

examples/bomberman/main.rs, src/core/components/animations.rs, src/core/components/material.rs, src/core/components/tiles/mod.rs, src/core/components/tiles/sprite.rs, src/core/components/tiles/tilemap.rs, src/rendering/bidimensional/gl_representations.rs, src/rendering/bidimensional/scion2d.rs, src/utils/maths.rs, src/utils/mod.rs
=> feat: Multi layered tilemap

Cargo.toml, examples/bomberman/main.rs, src/core/components/animations.rs, src/core/systems/animations_system.rs
=> feat(animation): Animation can now loop at start

examples/mario/main.rs, examples/taquin/main.rs, examples/world-cup/main.rs, src/core/components/animations.rs, src/core/systems/animations_system.rs, src/core/systems/ui_text_system.rs, src/rendering/bidimensional/scion2d.rs, src/utils/file.rs
Add color animations to be able to : 
Switch between color in a smooth way.
Create fadeIn, fadeOut animations 
FIXES #128
=> feat: color animations

examples/bomberman/bomb_system.rs, examples/bomberman/char_animations.rs, examples/bomberman/main.rs, examples/mario/character_control_system.rs, examples/tetris/systems/piece_system.rs, src/application.rs, src/core/components/animations.rs, src/core/components/maths/mod.rs, src/core/components/maths/transform.rs, src/core/components/maths/vector.rs, src/core/systems/ui_text_system.rs
=> feat: Vector and cleanup

examples/bomberman/bomb_animations.rs, examples/bomberman/char_animations.rs, examples/world-cup/main.rs, src/core/components/animations.rs
=> Feature animation constructors

examples/world-cup/main.rs, src/config/scion_config.rs, src/config/window_config.rs, src/core/components/color.rs, src/core/components/maths/collider.rs, src/core/components/maths/mod.rs, src/core/components/shapes/rectangle.rs, src/core/components/shapes/square.rs, src/core/components/shapes/triangle.rs, src/core/components/tiles/sprite.rs, src/core/components/tiles/tilemap.rs, src/core/components/tiles/tileset.rs, src/core/components/ui/ui_image.rs, src/core/components/ui/ui_text.rs, src/core/resources/events/mod.rs, src/core/resources/inputs/inputs_controller.rs, src/core/resources/inputs/keyboard.rs, src/core/resources/window.rs, src/utils/file.rs
=> feat: Add pivot on square and some docs

Cargo.toml, build.rs, examples/world-cup/main.rs, src/core/components/maths/transform.rs, src/core/components/shapes/line.rs, src/core/components/shapes/mod.rs, src/core/components/shapes/rectangle.rs, src/core/components/shapes/square.rs, src/core/components/tiles/sprite.rs, src/core/components/tiles/tilemap.rs, src/core/components/ui/ui_image.rs, src/core/components/ui/ui_text.rs, src/core/systems/collider_systems.rs, src/core/systems/default_camera_system.rs, src/core/systems/hide_propagation_system.rs, src/core/systems/parent_transform_system.rs, src/rendering/gl_representations.rs, src/rendering/mod.rs, src/rendering/renderer_state.rs, src/rendering/scion2d.rs, src/rendering/shaders/pipeline.rs
FIXES #144 
FIXES #143 
And also upgrade wgpu
=> feat: wgpu 0.10 && line component

examples/mario/main.rs, examples/tetris/layer.rs, src/application.rs, src/core/components/maths/camera.rs, src/core/components/maths/collider.rs, src/core/components/shapes/polygon.rs, src/core/systems/collider_systems.rs, src/core/systems/default_camera_system.rs
=> feat: Debug lines for colliders

src/core/resources/sound.rs, src/sound/context.rs, src/sound/controller.rs
Fixes #200 
Happy Hacktoberfest!
=> Add function and events for stopping all sounds

src/core/components/shapes/rectangle.rs
This pull request fixes https://github.com/grzi/scion/issues/193
=> Implement the Center pivot point for rectangle 

README.md
A few doc to help other contributors who are working on fedora like me :)
=> doc: fedora build packages

examples/bomberman/main.rs, examples/jezzball/main_scene.rs, examples/new-bark-town/assets/scenes/main_house_bedroom.json, examples/new-bark-town/scene.rs, examples/taquin/main.rs, examples/tetris/scene.rs, src/core/components/tiles/tilemap.rs, src/core/components/tiles/tileset.rs, src/core/resources/asset_manager.rs
=> feat(tilemap): Add events on tilemap and rework atlas

examples/jezzball/main_scene.rs, examples/taquin/animations.rs, examples/taquin/main.rs
=> feat(taquin): use animation on the taquin example

examples/tetris/scene.rs, src/core/components/ui/ui_text.rs, src/core/resources/asset_manager.rs, src/core/systems/ui_text_system.rs
=> feat(resources): Font in asset manager

examples/tetris/scene.rs, src/core/components/ui/mod.rs, src/core/components/ui/ui_input.rs, src/core/resources/focus_manager.rs, src/core/resources/inputs/inputs_controller.rs, src/core/resources/inputs/types.rs, src/core/resources/mod.rs, src/core/systems/focus_systems.rs, src/core/systems/missing_ui_component_system.rs, src/core/systems/mod.rs, src/core/systems/ui_input_systems.rs, src/core/systems/ui_text_system.rs, src/core/world.rs
=> Input text

examples/tetris/scene.rs, src/application.rs, src/core/components/ui/ui_image.rs, src/core/components/ui/ui_text.rs, src/core/resources/asset_manager.rs, src/core/systems/missing_ui_component_system.rs, src/core/systems/ui_text_system.rs, src/lib.rs, src/rendering/mod.rs, src/rendering/scion2d.rs
=> feat(ui): Using material component instead of path

examples/feature-showcase/main.rs, examples/feature-showcase/scene.rs, src/core/components/maths/mod.rs, src/core/components/shapes/line.rs, src/core/components/shapes/polygon.rs, src/core/components/shapes/rectangle.rs, src/core/components/shapes/square.rs, src/core/components/shapes/triangle.rs, src/core/components/tiles/sprite.rs, src/rendering/gl_representations.rs, src/rendering/mod.rs, src/rendering/scion2d.rs
=> feat(rendering): Pivot point should not impact default position

examples/feature-showcase/scene.rs, src/core/components/maths/mod.rs, src/core/components/maths/transform.rs, src/core/components/shapes/line.rs, src/core/components/shapes/polygon.rs, src/core/components/shapes/rectangle.rs, src/core/components/shapes/square.rs, src/core/components/shapes/triangle.rs, src/core/components/tiles/sprite.rs, src/core/systems/collider_systems.rs, src/core/systems/parent_transform_system.rs, src/rendering/gl_representations.rs, src/rendering/mod.rs, src/utils/maths.rs
=> feat(math): angle propagation + centroid + pivot for collision debug

src/core/resources/time.rs, src/lib.rs
FIXES #301 
FIXES #300 
FIXES #299
=> fix(reexports): Add Entity re-exports and fix error in timer

examples/jezzball/main.rs, examples/jezzball/systems/ball.rs, src/application.rs, src/core/components/maths/transform.rs, src/core/components/ui/ui_button.rs, src/core/resources/window.rs, src/core/systems/default_camera_system.rs, src/core/systems/ui_button_systems.rs, src/lib.rs, src/rendering/gl_representations.rs, src/rendering/renderer_state.rs
FIXES #307 
FIXES #306 
FIXES #305
=> fix(cursor): Smarter UI cursor reset, transform setX fn, dpi fix

src/core/resources/window.rs
=> fix(dpi): Fix division on window width/height

src/graphics/rendering/scion2d/renderer.rs, src/graphics/rendering/scion2d/rendering_thread.rs, src/graphics/rendering/scion2d/window_rendering_manager.rs
=> fix(window): Reducing on windows now stops rendering
